# Specifies the secret data for imagePullSecrets needed to fetch the private docker images
imageCredentials:
  create: true
  name: csp-registry-secret # example
  repositoryUriPrefix: "registry.aquasec.com" # for dockerhub - "docker.io"
  registry: "registry.aquasec.com" #REQUIRED only if create is true, for dockerhub - "index.docker.io/v1/"
  username: "andrey.khon@verygood.systems"
  password: "jarApnayd"
  email: "andrey.khon@verygood.systems"

rbac:
  enabled: true
  roleRef:

privileged: true

admin:
  token: "xxbvAVUg0qsoH8Ip7WnaJpqM8DIjx9emN3ny0erPQ2k3RCuK7c6jcIG--0a3KMCkOngBa2943fVkg4h0J4Fu0b3kyL18m-_R1WMaaZtrtHt33Ih64wzxK2buGZ7DrcsLuQryLja4L_o421bXiiDU9NlYc1VelHwzunXcmt-0SoLjulRhn4_BjNto0ixTa3sXFNT5sefUUmP4voNNDcj0bxNtZH2RWEYB85o3FFOcv0amegoAXjKWuOnHnokgmAZL2c2kaoWNE63h-RUpcnxB67mAuOetdM0eU8hREQBRCnM0wuRNjJ3OEhFXpO-uMxhGmDEZTXKIQbfn-vpQVQsD_MBrPH44VMiTP4Wwz6DrAdaJktgzmqBBR7R5e6qtIweKo7O7YoXd67Wrw8rNmSQTagQSzsg9wayndObN7aCSQFoTJfI4aheTWAV3J4nxP8jQJqrx3VSktxEpEM0_scThU8UM3lbxNmWH0npOof_dK3vCpGWjW5YWjIwArlgaINXdgXgFeq5K93TqmdPURnniZU5puA=="
  password: vgs-aqua-password
  clustermode: false

docker:
  socket:
    path: /var/run/docker.sock # pks - /var/vcap/data/sys/run/docker/docker.sock

dockerless: false

db:
  external:
    enabled: false
    name:
    host:
    port:
    user:
    password:
    auditName:
    auditHost:
    auditPort:
    auditUser:
    auditPassword:
  ssl: false
  auditssl: false
  image:
    repository: database
    tag: "4.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  persistence:
    enabled: true
    storageClass:
    size: 30Gi
    accessMode: ReadWriteOnce
  livenessProbe:
    exec:
      command:
      - sh
      - -c
      - exec pg_isready --host $POD_IP
    initialDelaySeconds: 60
    timeoutSeconds: 5
    failureThreshold: 6
  readinessProbe:
    exec:
      command:
      - sh
      - -c
      - exec pg_isready --host $POD_IP
    initialDelaySeconds: 5
    timeoutSeconds: 3
    periodSeconds: 5
  resources:
    requests:
      cpu: 0.1
      memory: 0.2Gi
    limits:
      cpu: 1
      memory: 1Gi
  nodeSelector: {}
  tolerations: []
  affinity: {}

gate:
  image:
    repository: gateway
    tag: "4.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    externalPort: 3622
  publicIP: aqua-gateway
  replicaCount: 1
  livenessProbe: {}
  readinessProbe: {}
  resources:
    requests:
      cpu: 0.1
      memory: 0.2Gi
    limits:
      cpu: 1
      memory: 2Gi
  nodeSelector: {}
  tolerations: []
  affinity: {}

web:
  image:
    repository: console
    tag: "4.0"
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    externalPort: 8080
  encryptionKey:
  ingress:
    enabled: false
    annotations: {}
    #  kubernetes.io/ingress.class: nginx
    hosts: #REQUIRED
    #- aquasec-test.example.com
    tls: []
    #  - secretName: aquasec-tls
    #    hosts:
    #      - aquasec.domain.com
  replicaCount: 1
  livenessProbe: {}
  readinessProbe: {}
  resources:
    requests:
      cpu: 0.1
      memory: 0.2Gi
    limits:
      cpu: 1
      memory: 2Gi
  nodeSelector: {}
  tolerations: []
  affinity: {}

scanner:
  enabled: false
  image:
    repository: scanner
    tag: "4.0"
    pullPolicy: IfNotPresent
  user:
  password:
  replicaCount: 1
  livenessProbe: {}
  readinessProbe: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
